// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vie_lich/models/su_kien.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SuKienAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SuKienAdapter());
  }
}
